In [54]:
import numpy as np
def cal(x1, x2, y):
    loc = np.array([0, 0, 0])
    delta = 1.0
    t = 0
    loss = np.sum(y)
    while (delta > 0):
        minloss = 1000000000
        minv = np.array([0, 0, 0])
        for v1 in range(-1, 2):
            for v2 in range(-1, 2):
                for v3 in range(-1, 2):
                    v = np.array([v1*0.01, v2*0.01, v3*0.01])
                    temploc = loc + v
                    tempans = temploc[0]*x1 + temploc[1]*x2 + temploc[2]
                    temploss = np.sum(np.abs(tempans - y))
                    if(temploss < minloss):
                        minloss = temploss
                        minv = v
        loc = loc + minv*delta*100
        delta = (minloss/loss)**0.5
        if(t == 1000):
            break
        t += 1
    return loc

a = np.loadtxt("E:/forjianmo/datafortest.txt")
cal(a[:, 0], a[:, 1], a[:, 2])
print("wtf")

[ 1.  1.  1.]
99519750.0
***
0.997496115431
[ 1.99749612  1.99749612  1.99749612]
49494750.06
***
0.703454711331
[ 1.99749612  2.70095083  2.70095083]
98684.2410456
***
0.0314109070458
[ 1.99749612  2.73236173  2.73236173]
88792.4610947
***
0.0297950845197
[ 1.99749612  2.76215682  2.76215682]
88387.6452421
***
0.0297270871846
[ 1.99749612  2.79188391  2.79188391]
88006.5667861
***
0.0296629346142
[ 1.99749612  2.82154684  2.82154684]
87629.1850741
***
0.0295992673459
[ 1.99749612  2.85114611  2.85114611]
87255.4317307
***
0.0295360769456
[ 1.99749612  2.88068218  2.88068218]
86885.2823035
***
0.0294733623331
[ 1.99749612  2.91015555  2.91015555]
86518.714468
***
0.0294111227574
[ 1.99749612  2.93956667  2.93956667]
86155.702467
***
0.0293493568536
[ 1.99749612  2.96891603  2.96891603]
85796.2243942
***
0.0292880638794
[ 1.99749612  2.99820409  2.99820409]
85440.2555185
***
0.0292272425802
[ 1.99749612  3.02743133  3.02743133]
85087.7745323
***
0.0291668922548
[ 1.99749612  3.05659823 